{
    "meta":{
        "$ver":0,
        "creator":"IambicCave",
        "background":"Malody_Icon.png",
        "version":"",
        "preview":1145,
        "id":0,
        "mode":0,
        "time":1684573284,
        "song":{
            "title":"_temp_1681485898",
            "artist":"DEMO",
            "id":0
        },
        "mode_ext":{
            "column":4,
            "bar_begin":0
        }
    },
    "time":[
        {
            "beat":[
                0,
                0,
                1
            ],
            "bpm":180
        },
        {
            "beat":[
                3,
                0,
                1
            ],
            "bpm":360
        }
    ],
    "effect":[
        {
            "beat":[
                0,
                0,
                1
            ],
            "scroll":0.8
        },
        {
            "beat":[
                6,
                1,
                256
            ],
            "scroll":-2.0
        },
        {
            "beat":[
                7,
                0,
                1
            ],
            "scroll":1.0
        }
    ],
    "note":[
        {
            "beat":[
                0,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                0,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                1,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                1,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                2,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                2,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                3,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                3,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                4,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                4,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                5,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                5,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                6,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                6,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                7,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                7,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                8,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                8,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                9,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                9,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                10,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                10,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                11,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                11,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                12,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                12,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                13,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                13,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                14,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                14,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                15,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                15,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                16,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                16,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                17,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                17,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                18,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                18,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                19,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                19,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                20,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                20,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                21,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                21,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                22,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                22,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                23,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                23,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                24,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                24,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                25,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                25,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                26,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                26,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                27,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                27,
                2,
                4
            ],
            "column":3
        },
        {
            "beat":[
                28,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                28,
                2,
                4
            ],
            "column":1
        },
        {
            "beat":[
                29,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                29,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                29,
                0,
                4
            ],
            "column":3
        },
        {
            "beat":[
                0,
                0,
                1
            ],
            "sound":"1681485898.ogg",
            "vol":100,
            "offset":295,
            "type":1
        }
    ],
    "extra":{
        "test":{
            "divide":4,
            "speed":100,
            "save":0,
            "lock":0,
            "edit_mode":0
        }
    }
}