{
    "meta":{
        "$ver":0,
        "creator":"IambicCave",
        "background":"",
        "version":"",
        "id":0,
        "mode":0,
        "time":1681485956,
        "song":{
            "title":"_temp_1681485898",
            "artist":"Unknown",
            "id":0
        },
        "mode_ext":{
            "column":4,
            "bar_begin":0
        }
    },
    "time":[
        {
            "beat":[
                0,
                0,
                1
            ],
            "bpm":180
        }
    ],
    "note":[
        {
            "beat":[
                29,
                0,
                4
            ],
            "column":0
        },
        {
            "beat":[
                29,
                0,
                4
            ],
            "column":2
        },
        {
            "beat":[
                31,
                1,
                4
            ],
            "column":1
        },
        {
            "beat":[
                0,
                0,
                1
            ],
            "sound":"1681485898.ogg",
            "vol":100,
            "offset":295,
            "type":1
        }
    ],
    "extra":{
        "test":{
            "divide":4,
            "speed":100,
            "save":0,
            "lock":0,
            "edit_mode":0
        }
    }
}